#!/bin/bash

options="CONFIG_BUILD_ROM_CODE=0 OT_FTD=0 CONFIG_PDS_ENABLE=1 OT_CLI=0 CONFIG_CHIP_REVISION=A1"

options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-sed-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 2>&1 | tee build_out/make.log

exit $?
