#!/bin/sh

# build for demo image
# build options,
#   CONFIG_CHIP_REVISION, A0/A1 chip revision
CONFIG_CHIP_REVISION=A1

CONFIG_BUILD_ROM_CODE=0

options="OT_NCP=0 CONFIG_DISABLE_PRINT=1 CONFIG_SYS_AOS_CLI_ENABLE=0 CONFIG_OPENTHREAD_CLI_ENABLE=1"
options=$options" CONFIG_BUILD_ROM_CODE=${CONFIG_BUILD_ROM_CODE} CONFIG_CHIP_REVISION=${CONFIG_CHIP_REVISION}"
options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-ncp_rcp-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 2>&1 | tee build_out/make.log

exit $?
