#!/bin/bash

# build for demo image
# build options, 
#   CONFIG_FTD, for thread device type
#       1, build for thread FTD image, 
#       0, build for thread MTD image
#   CONFIG_PREFIX, set prefix for command cli
CONFIG_FTD=1
CONFIG_PREFIX=
#CONFIG_PREFIX=otc

CONFIG_LINK_METRICS=1
CONFIG_CSL_RX=1
CONFIG_ENABLE_FP=1
# OPENTHREAD_TESTS_UNIT=1

jobs=4
if (( $1 -eq "" )); then
jobs=$1
fi

if [ ! -d build_out ]; then
mkdir build_out
fi

options="CONFIG_CPP_ENABLE=1 \
    CONFIG_FTD=$CONFIG_FTD \
    CONFIG_TIMESYNC=0 \
    CONFIG_LINK_METRICS=$CONFIG_LINK_METRICS \
    CONFIG_CSL_RX=$CONFIG_CSL_RX"

options=$options" CONFIG_ENABLE_FP=$CONFIG_ENABLE_FP"

if [[ "$CONFIG_PREFIX" != "" ]]; then
    options=$options" CONFIG_PREFIX=\"$CONFIG_PREFIX\""
fi

if [[ "$OPENTHREAD_TESTS_UNIT" != "" ]]; then
    options=$options" OPENTHREAD_TESTS_UNIT=$OPENTHREAD_TESTS_UNIT"
fi

options=$options" CONFIG_OPENTHREAD_CLI_ENABLE=1"

options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"third_party/mbedtls/mbedtls-config.h\""

make $options -j $jobs 2>&1 | tee build_out/make.log

exit $?
