#!/bin/sh

# build for demo image
# build options,
#   OT_FTD, for thread device type
#       1, build for thread FTD image,
#       0, build for thread MTD image
OT_FTD=1
CONFIG_BUILD_ROM_CODE=1

options="OT_NCP=1 OT_FTD=${OT_FTD} CONFIG_DISABLE_PRINT=1 CONFIG_OPENTHREAD_CLI_ENABLE=1"
options=$options" CONFIG_BUILD_ROM_CODE=1"
options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-ncp_rcp-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 2>&1 | tee build_out/make.log

exit $?
