#!/bin/sh

# build for RCP mode image
# build options,

# RCP mode: CONFIG_OT_RCP=1
CONFIG_OT_FTD=1

# NCP mode with CLI enabled
options="CONFIG_OT_NCP=1 CONFIG_OT_FTD=${CONFIG_OT_FTD} CONFIG_OPENTHREAD_CLI_ENABLE=1 CONFIG_DISABLE_PRINT=1"
options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-ncp_rcp-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 2>&1 | tee build_out/make.log

exit $?
