#
#compiler flag config domain
#

#
#board config domain
#


#
#app specific config domain
#

CONFIG_CHIP_NAME := BL702L

# CONFIG_CACHE_SIZE := 8192


CONFIG_USE_STDLIB_MALLOC := 0

CONFIG_BUILD_ROM_CODE := 0
CONFIG_DBG_RUN_ON_FPGA := 0

CONFIG_EM_SIZE := 16
CONFIG_BT := 0
CONFIG_CIS := 0
CONFIG_ADV_EXTENSION := 0
CONFIG_BIS := 0
CONFIG_LE_PWR_CTRL := 0
CONFIG_CTE := 0

CONFIG_EASYFLASH_ENABLE:=1
CONFIG_USE_PSRAM := 0

# use internal RC32K by default; may set to 1 for better accuracy if there is XTAL32K on the board
CONFIG_USE_XTAL32K := 1 

ifeq ($(CONFIG_PDS_ENABLE),1)
CONFIG_PDS_LEVEL ?= 31
ifeq ($(CONFIG_PDS_LEVEL),31)
CONFIG_PDS_CPU_PWROFF := 1
endif
endif

# if CONFIG_PDS_CPU_PWROFF is defined, CONFIG_LINK_CUSTOMER must be defined to avoid linking the default .ld file
ifeq ($(CONFIG_PDS_CPU_PWROFF),1)
#CONFIG_LINK_CUSTOMER := 1
endif

CONFIG_BL702_USE_ROM_DRIVER := 1

LOG_ENABLED_COMPONENTS := hosal vfs

CONF_ENABLE_COREDUMP:=1

CONFIG_SYS_COMMON_MAIN_ENABLE := 1
CONFIG_SYS_APP_TASK_STACK_SIZE := 2048
CONFIG_SYS_APP_TASK_PRIORITY := 14
CONFIG_SYS_BLOG_ENABLE := 1

ifneq ($(CONFIG_PDS_ENABLE),1)
CONFIG_SYS_VFS_ENABLE := 1
CONFIG_SYS_VFS_UART_ENABLE := 1
ifdef CONFIG_PREFIX
	CONFIG_SYS_AOS_CLI_ENABLE := 1
else
	CONFIG_SYS_AOS_CLI_ENABLE := 0
endif
CONFIG_SYS_AOS_LOOP_ENABLE := 1
endif

EXT_CFG_FILE := $(PROJECT_PATH)/proj_config_ext.mk
ifeq ($(EXT_CFG_FILE), $(wildcard $(EXT_CFG_FILE)))
include $(PROJECT_PATH)/proj_config_ext.mk
endif

CONFIG_DATA_POLL_CSMA := 1 
CONFIG_OPENTHREAD := 1
CONFIG_OT_ROM_ENABLE := 1

CONFIG_MBEDTLS_BIGNUM_USE_HW := 1
CONFIG_MBEDTLS_AES_USE_HW := 1
CONFIG_MBEDTLS_ECC_USE_HW := 1
CONFIG_MBEDTLS_SHA256_USE_HW := 1
