#!/bin/bash

# build for demo image
# build options, 
#   OT_FTD, for thread device type
#       1, build for thread FTD image, 
#       0, build for thread MTD image
#   CONFIG_USE_WIFI_BR, for connectivity to infra network interface
#       1, using Wi-Fi for infra network interface, which needs   
#       0, disable CDC
OT_FTD=1
CONFIG_USE_WIFI_BR=1
CONFIG_THREAD_AUTO_START=1

CONFIG_PREFIX=otc
CONFIG_USB_CDC=0

options="CONFIG_USB_CDC=$CONFIG_USB_CDC OT_FTD=$OT_FTD OT_CLI=1 CONFIG_OTBR=1"
if [[ "$CONFIG_PREFIX" != "" ]]; then
    options=$options" CONFIG_PREFIX=$CONFIG_PREFIX"
fi
options=$options" CONFIG_THREAD_AUTO_START=$CONFIG_THREAD_AUTO_START" 

if [[ "$CONFIG_USE_WIFI_BR" == "0" ]] || [[ "$CONFIG_USE_WIFI_BR" == "" ]]; then
    CONFIG_USB_CDC=0
fi
options=$options" CONFIG_USE_WIFI_BR=$CONFIG_USE_WIFI_BR" 

options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-br-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 2>&1 | tee build_out/make.log

exit $?
