#!/bin/sh

# build for demo image
# build options,
#   CONFIG_NCP, for NCP mode
#       1, works as NCP, and CONFIG_FTD is valid to configure to FTD/MTD
#       0, works as RCP, and CONFIG_FTD is not valid
#   CONFIG_FTD, for thread device type, if CONFIG_NCP = 1
#       1, build for thread FTD image,
#       0, build for thread MTD image
CONFIG_NCP=1
CONFIG_FTD=1
CONFIG_USB_CDC=0
CONFIG_ENABLE_FP=0

OPENTHREAD_RADIO=0
CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION=4

jobs=4
if (( $1 -eq "" )); then
jobs=$1
fi

if [ ! -d build_out ]; then
mkdir build_out
fi

options="CONFIG_USB_CDC=$CONFIG_USB_CDC CONFIG_ENABLE_FP=$CONFIG_ENABLE_FP CONFIG_CPP_ENABLE=1 \
    CONFIG_NCP=$CONFIG_NCP"

if [ "$CONFIG_NCP" == "1" ]; then
    options=$options" CONFIG_FTD=$CONFIG_FTD"
else
    OPENTHREAD_RADIO=1
fi

options=$options" CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION=$CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION"
options=$options" OPENTHREAD_RADIO=$OPENTHREAD_RADIO"
options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"third_party/mbedtls/mbedtls-config.h\""

make $options -j $jobs 2>&1 | tee build_out/make.log

exit $?
