#!/bin/bash

# build for demo image
# build options, 
#   CONFIG_FTD, for thread device type
#       1, build for thread FTD image, 
#       0, build for thread MTD image
#   CONFIG_PREFIX, set prefix for command.
#   CONFIG_USB_CDC, for cli command line build,
#       1, enable CDC  
#       0, disable CDC
#   CONFIG_BT_OAD_SERVER, for cli command line build, 
#       1, enable OTA upgrade feature over BLE
#       0, disable OTA upgrade feature over BLE
CONFIG_FTD=1
CONFIG_PREFIX=otc
CONFIG_USB_CDC=0
CONFIG_BT_OAD_SERVER=0
CONFIG_DISABLE_PRINT=0
# OPENTHREAD_TESTS_UNIT=1

CONFIG_TIMESYNC=0
CONFIG_LINK_METRICS=1
CONFIG_CSL_RX=1

OPENTHREAD_RADIO=0
CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION=4

jobs=4
if (( $1 -eq "" )); then
jobs=$1
fi

CONFIG_ENABLE_FP=0
if [ ! -d build_out ]; then
mkdir build_out
fi

if [ $CONFIG_BT_OAD_SERVER -eq "1" ]; then
options="CONFIG_USB_CDC=$CONFIG_USB_CDC CONFIG_ENABLE_FP=$CONFIG_ENABLE_FP CONFIG_CPP_ENABLE=1 \
    CONFIG_BT=1 CONFIG_BT_OAD_SERVER=1 \
    CONFIG_FTD=$CONFIG_FTD \
    CONFIG_TIMESYNC=$CONFIG_TIMESYNC \
    CONFIG_LINK_METRICS=$CONFIG_LINK_METRICS \
    CONFIG_CSL_RX=$CONFIG_CSL_RX"

else
options="CONFIG_USB_CDC=$CONFIG_USB_CDC CONFIG_ENABLE_FP=$CONFIG_ENABLE_FP CONFIG_CPP_ENABLE=1 \
    CONFIG_FTD=$CONFIG_FTD \
    CONFIG_TIMESYNC=$CONFIG_TIMESYNC \
    CONFIG_LINK_METRICS=$CONFIG_LINK_METRICS \
    CONFIG_CSL_RX=$CONFIG_CSL_RX"
fi

if [[ "$CONFIG_PREFIX" != "" ]]; then
    options=$options" CONFIG_PREFIX=$CONFIG_PREFIX"
fi

if [[ "$OPENTHREAD_TESTS_UNIT" != "" ]]; then
    options=$options" OPENTHREAD_TESTS_UNIT=$OPENTHREAD_TESTS_UNIT"
fi

if [[ "$2" != "" ]]; then
    CONFIG_USB_CDC_PID=`echo $2 | awk -F':' '{print $1}'`
    CONFIG_USB_CDC_VID=`echo $2 | awk -F':' '{print $2}'`

    if [[ "$CONFIG_USB_CDC_VID" != "" ]] && [[ "$CONFIG_USB_CDC_PID" != "" ]]; then
        options=$options" CONFIG_USB_CDC_VID=0x${CONFIG_USB_CDC_VID} CONFIG_USB_CDC_PID=0x${CONFIG_USB_CDC_PID}"

        if [[ "$3" != "" ]]; then
            CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION=$3
            options=$options" CONFIG_GOLDEN_UNIT=1"
        fi
    fi
fi

options=$options" CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION=$CONFIG_OPENTHREAD_CONFIG_THREAD_VERSION"
options=$options" OPENTHREAD_RADIO=$OPENTHREAD_RADIO"

if [ $CONFIG_DISABLE_PRINT -eq "1" ]; then
    options=$options" CONFIG_DISABLE_PRINT=${CONFIG_DISABLE_PRINT}"
fi

options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"third_party/mbedtls/mbedtls-config.h\""

make $options -j $jobs 2>&1 | tee build_out/make.log

exit $?
