#!/bin/sh

# build for demo image
options="OT_NCP=0 CONFIG_DISABLE_PRINT=1"
options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-ncp_rcp-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 >&1 | tee build_out/make.log

exit $?
