#!/bin/sh

# build for demo image
# build options,
#   CONFIG_OT_FTD, for thread device type
#       1, build for thread FTD image,
#       0, build for thread MTD image
#   CONFIG_BT, for BLE controller on UART 1 with PIN 3/4
#       1, enable BLE controller
#       0, disable BLE controller
CONFIG_OT_FTD=1
CONFIG_BT=0

# NCP mode with CLI enabled
options="CONFIG_OT_NCP=1 CONFIG_OT_FTD=${CONFIG_OT_FTD} CONFIG_OPENTHREAD_CLI_ENABLE=1 CONFIG_DISABLE_PRINT=1"
options=$options" CONFIG_BT=${CONFIG_BT}"
options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-ncp_rcp-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""

if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 >&1 | tee build_out/make.log

exit $?
