#!/bin/bash

options="CONFIG_OT_CLI=shell CONFIG_OT_FTD=0 CONFIG_SYS_AOS_CLI_ENABLE=1 CONFIG_PREFIX=otc CONFIG_USB_CDC=0"
options=$options" CONFIG_BT=1"

options=$options" CONFIG_EXTMBEDTLS_CONFIG_FILE=\"mbedtls_proj_config.h\""
options=$options" CONFIG_OPENTHREAD_FILE=\"openthread-core-cli-config.h\""
options=$options" CONFIG_OPENTHREAD_CHECK_FILE=\"openthread-core-platform-config-check.h\""


if [ ! -d build_out ]; then
mkdir build_out
fi
make $options -j4 2>&1 | tee build_out/make.log

exit $?